### ISSUE TITLE
The "run_image" job should be in the PR workflow

### ISSUE THREAD

**Issue by JasonFreeberg** [bernie-graves/R-Shiny-Dashboard#4]
I noticed the following job is in the workflow that builds and pushes the image to DockerHub (run-docker-image.yaml)

```yaml
  run_image:
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: pull the image from dockerhub
        run: docker pull berniegraves/shiny-dashboard:main
      - name: Run the iamge
        run: docker run -dp 3838:3838 berniegraves/shiny-dashboard:main
```

You should move that job to the the other workflow (docker-build.yaml) and run it there. The docker-build.yaml workflow runs whenever there's a PR on the repository, so the idea is that run-docker-image.yaml builds the image, runs it, and send a request to it. If the request has an expected response, then you know that the PR's changes didn't drastically break the container.

Message me if you have questions
